version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: "@sentry/react"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
    - 6.3.2
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.14
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.8
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@tailwindcss/postcss7-compat"
    versions:
    - 2.0.3
    - 2.0.4
    - 2.1.0
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: "@sentry/tracing"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
  - dependency-name: unsplash-js
    versions:
    - 7.0.3
  - dependency-name: reactstrap
    versions:
    - 8.9.0
  - dependency-name: standard-version
    versions:
    - 9.1.0
  - dependency-name: node-sass
    versions:
    - 5.0.0
  - dependency-name: react-toastify
    versions:
    - 7.0.3
  - dependency-name: "@craco/craco"
    versions:
    - 6.1.1
