version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12.16.1
        steps:
            - checkout
            - run:
                  name: Install
                  command: npm install
            - run:
                  name: Build
                  command: yarn build
orbs:
    node: circleci/node@3.0.0
workflows:
    build:
        jobs:
            - build
